package util;

public enum Stat {
    FLAT_ATK,
    FLAT_DEF,
    FLAT_HP,
    ATK_PERCENT,
    DEF_PERCENT,
    HP_PERCENT,

    ELEMENTAL_MASTERY,
    ENERGY_RECHARGE,

    PHYS_DMG_BONUS,
    PYRO_DMG_BONUS,
    CRYO_DMG_BONUS,
    HYDRO_DMG_BONUS,
    ELECTRO_DMG_BONUS,
    ANEMO_DMG_BONUS,
    GEO_DMG_BONUS,
    DENDRO_DMG_BONUS,

    CRIT_RATE,
    CRIT_DMG,
    HEALING_BONUS
}
